version: '3.8'

services:
  django_service: &django_service
    build: ./api
    image: "django_service:dev"
    container_name: django_service
    command: >
      sh -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - "./django/:/src"
    environment:
      DJANGO_SUPERUSER_PASSWORD: "admin"
      DJANGO_SUPERUSER_USERNAME: "root"
      DJANGO_SUPERUSER_EMAIL: "email@example.com"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - dev-net

  db:
    image: 'postgres:14.2'
    restart: "no"
    container_name: database_service
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: django_service
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "8001:5432"
    networks:
      dev-net:


networks:
  dev-net:
    name: dev-net

