# Generated by Django 3.2.5 on 2022-06-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retrieve_count',
            field=models.IntegerField(default=0),
        ),
    ]
